[package]
name = "docx_api"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = { version = "1.6.1", features = ["macros"] }
lambda = { git = "https://github.com/awslabs/aws-lambda-rust-runtime/", branch = "master"}
serde_json = "1.0"